# Generated by Django 4.0.4 on 2022-05-04 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('date_arrive', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('height', models.IntegerField(verbose_name='height')),
                ('special_signs', models.CharField(max_length=200, verbose_name='special_signs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
            },
        ),
    ]
